Develop
tonikromik/petstoreSpringBoot pull request #14
Opened 2023-05-15 09:23 UTC by tonikromik

2023-05-19 06:58 UTC, financeasist requested changes

2023-05-19 07:08 UTC, tonikromik commented on src/main/java/com/petstore/controller/StoreController.java
> +    private final OrdersMapper ordersMapper;
moved

2023-05-19 07:16 UTC, tonikromik commented on src/main/java/com/petstore/controller/UserController.java
> +    @PostMapping()
removed

2023-05-19 07:34 UTC, tonikromik commented on src/main/java/com/petstore/controller/StoreController.java
> +    private final StoreService ordersService;
renamed

2023-05-19 07:36 UTC, tonikromik commented on src/main/java/com/petstore/dto/CategoryDTO.java
> +//@Builder
refactored

2023-05-22 03:00 UTC, tonikromik commented on src/main/java/com/petstore/dto/UserDTO.java
>      private Long id;
fixed

2023-05-22 03:11 UTC, tonikromik commented on src/main/java/com/petstore/entity/Category.java
> +    private List<Pet> pets = new ArrayList<>();
done

2023-05-22 03:11 UTC, tonikromik commented on src/main/java/com/petstore/entity/Orders.java
>  @NoArgsConstructor
refactored

2023-05-22 03:42 UTC, tonikromik commented on src/main/java/com/petstore/entity/Pet.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
done

2023-05-22 03:42 UTC, tonikromik commented on src/main/java/com/petstore/entity/Tag.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tags_seq")
done

2023-05-22 06:51 UTC, tonikromik commented on src/main/java/com/petstore/entity/User.java
> +    @Column(name = "email", nullable = false)
done

2023-05-22 13:27 UTC, tonikromik commented on src/main/java/com/petstore/mapper/CategoryMapper.java
> +//    void updateProperties(CategoryDTO dto, @MappingTarget Category entity);
cleaned and refactored

2023-05-22 13:29 UTC, tonikromik commented on src/main/java/com/petstore/mapper/TagMapper.java
> +//    void updateProperties(TagDTO dto, @MappingTarget Tag entity);
refactored

2023-05-22 13:37 UTC, tonikromik commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +    }
done

2023-05-22 13:52 UTC, tonikromik commented on src/main/java/com/petstore/entity/Category.java
> +@AllArgsConstructor
added

2023-05-22 14:10 UTC, tonikromik commented on src/main/java/com/petstore/entity/Orders.java
>      private String shipDate;
Changed

2023-05-22 17:17 UTC, tonikromik commented on src/main/java/com/petstore/entity/Orders.java
>      private Long petId;
changed

2023-05-22 17:23 UTC, tonikromik commented on src/main/java/com/petstore/service/PetService.java
> +     * Adds a new pet based on the provided PetDTO object.
added

2023-05-22 17:23 UTC, tonikromik commented on src/main/java/com/petstore/service/PetService.java
> +    void updatePet(PetDTO petDTO);
changed

2023-05-22 17:25 UTC, tonikromik commented on src/main/java/com/petstore/service/PetService.java
> +    void init();
done

2023-05-22 17:25 UTC, tonikromik commented on src/main/java/com/petstore/service/StoreService.java
> +    Orders saveOrder(Orders order);
done

2023-05-22 17:29 UTC, tonikromik commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +        Set<Tag> tags = tagMapper.toSetEntities(petDTO.getTags());
changed

2023-05-22 17:29 UTC, tonikromik commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +    private final Path root = Paths.get("uploads");
done

2023-05-22 17:34 UTC, tonikromik commented on src/main/java/com/petstore/dto/UserDTO.java
>  @Builder
BaseDTO doesn't have fields so it isn't necessary.

2023-05-22 17:36 UTC, tonikromik commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +            throw new IllegalArgumentException(INVALID_VALUE);
I want to send my message. Do I need to make my custom exception?

2023-05-25 12:10 UTC, financeasist commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +            throw new IllegalArgumentException(INVALID_VALUE);
in that case custom will be better

2023-05-25 12:10 UTC, financeasist commented on src/main/java/com/petstore/service/impl/PetServiceImpl.java
> +            throw new IllegalArgumentException(INVALID_VALUE);
in that case custom will be better

2023-05-25 12:26 UTC, financeasist approved these changes

2023-05-25 12:27 UTC, financeasist approved these changes

2023-05-25 12:30 UTC, financeasist approved these changes

2023-05-25 12:31 UTC, merged