Added security and open api
tonikromik/petstoreSpringBoot pull request #20
Opened 2023-06-07 11:02 UTC by tonikromik

#16 Added Security to the project and #10 open API description.

2023-06-09 15:36 UTC, financeasist requested changes

2023-06-09 15:36 UTC, financeasist commented on src/main/java/com/petstore/controller/StoreController.java
> +//    @PreAuthorize("hasRole('USER')")
clean up commented code

2023-06-12 18:46 UTC, tonikromik commented on src/main/java/com/petstore/controller/StoreController.java
> +//    @PreAuthorize("hasRole('USER')")
done

2023-06-12 18:47 UTC, tonikromik commented on README.md
> +- import a project to IDE and run PetstoreApplication.java
Yes. Updated

2023-06-13 13:10 UTC, financeasist approved these changes

2023-06-13 13:10 UTC, merged